image: node:latest

cache:
  paths:
    - node_modules/

before_script:
    - npm install -g grunt-cli
    - npm install

build:
  stage: build
  script:
    - grunt build

test:
  stage: test
  script:
    - grunt test
