image: node:14

cache:
  paths:
    - node_modules/

stages:
  - build
  - test

before_script:
  - node -v
  - npm install -g grunt-cli
  - npm install

build:
  stage: build
  script:
    - grunt build

checkstyle:
  stage: build
  script:
    - grunt checkstyle
  allow_failure: true

test:
  stage: test
  script:
    - grunt test
